//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamexEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamexContext : DbContext
    {
        public GamexContext()
            : base("name=GamexContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountBookmark> AccountBookmark { get; set; }
        public virtual DbSet<AccountStatus> AccountStatus { get; set; }
        public virtual DbSet<ActivityHistory> ActivityHistory { get; set; }
        public virtual DbSet<Agenda> Agenda { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Booth> Booth { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyBookmark> CompanyBookmark { get; set; }
        public virtual DbSet<CompanyStatus> CompanyStatus { get; set; }
        public virtual DbSet<Exhibition> Exhibition { get; set; }
        public virtual DbSet<ExhibitionAttendee> ExhibitionAttendee { get; set; }
        public virtual DbSet<ProposedAnswer> ProposedAnswer { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Reward> Reward { get; set; }
        public virtual DbSet<RewardHistory> RewardHistory { get; set; }
        public virtual DbSet<Survey> Survey { get; set; }
        public virtual DbSet<SurveyAnswer> SurveyAnswer { get; set; }
        public virtual DbSet<SurveyParticipation> SurveyParticipation { get; set; }
    }
}
