//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamexEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyAnswer
    {
        public int QuestionId { get; set; }
        public Nullable<int> ProposedAnswerId { get; set; }
        public string AccountId { get; set; }
        public int SurveyId { get; set; }
        public string Other { get; set; }
        public int SurveyAnswerId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ProposedAnswer ProposedAnswer { get; set; }
        public virtual Question Question { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
